url: https://neuroinfo-os.github.io

# Site settings
title: Cognition Research Hub UOS
email: your-email@domain.com
description: "The Cognition research hub at University Osnabrück is an initiative
to focus research efforts across Cognitive Science, Computer Science, Biology
Linguistics and Psychology towards research into what the distinguishing 
attributes that have led to the phenomenom of human cognition are."
# TODO: The description needs updates!



# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# permalinking for posts?